import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars = {
    docs: [
        {
            className: "sb-cat-developer",
            collapsed: false,
            items: [
                {
                    className: "sb-doc-site-contract",
                    id: "developer/index",
                    label: "📚 Developer Docs",
                    type: "doc",
                },
                {
                    className: "sb-doc-site-contract",
                    id: "developer/docusaurus-site-contract",
                    label: "🧭 Docusaurus Site Contract",
                    type: "doc",
                },
                {
                    className: "sb-doc-site-contract",
                    id: "developer/deploy-pages-seo-and-indexnow",
                    label: "🌐 Pages SEO + IndexNow",
                    type: "doc",
                },
                {
                    className: "sb-cat-api-overview",
                    collapsed: true,
                    items: [
                        {
                            dirName: "developer/api",
                            type: "autogenerated",
                        },
                    ],
                    label: "📘 API Reference (TypeDoc)",
                    link: {
                        description:
                            "Generated API documentation from src/plugin.ts and internal modules.",
                        title: "API Reference",
                        type: "generated-index",
                    },
                    type: "category",
                },
            ],
            label: "🛠️ Developer",
            link: {
                description:
                    "Contributor docs, site contract guidance, and generated API reference.",
                title: "Developer",
                type: "generated-index",
            },
            type: "category",
        },
        {
            className: "sb-cat-dev-links",
            collapsed: true,
            items: [
                {
                    href: "https://tsdoc.org",
                    label: "📘 TSDoc",
                    type: "link",
                },
                {
                    href: "https://typedoc.org",
                    label: "📗 TypeDoc",
                    type: "link",
                },
                {
                    href: "https://www.npmjs.com/package/eslint-plugin-tsdoc-require-2",
                    label: "📦 NPM package",
                    type: "link",
                },
                {
                    href: "https://github.com/Nick2bad4u/eslint-plugin-tsdoc-require-2",
                    label: "🐙 GitHub repository",
                    type: "link",
                },
            ],
            label: "🔗 External Links",
            link: {
                title: "External Links",
                type: "generated-index",
            },
            type: "category",
        },
    ],
} satisfies SidebarsConfig;

export default sidebars;
